### ISSUE TITLE
boost dependencies vs compiler dependencies (C++14 or above)

### ISSUE THREAD

**Issue by haianos** [orocos-toolchain/orocos_toolchain#35]
Up to know, Orocos heavily depends on boost libraries. For example, `slotFunction`s (cf event ports) need a `boost::function`.
However, now with modern C++ (C++14 or above), all these are in `std`.
Does anyone has considered pro/cons to refactor all in favor of `std` libraries, considering the level of maturity of the compilers in C++14 nowadays?

**Comment by meyerj** [comment]
> Does anyone has considered pro/cons to refactor all in favor of std libraries, considering the level of maturity of the compilers in C++14 nowadays?

Not that I am aware of. We do use some C++11 features in RTT if it is compiled in C++11 mode or newer, but only in the implementation (in source files) and some unit tests, not in header files.

Updating all usages of `boost::bind`, `boost::function` or `boost::shared_ptr` by the respective C++11 counterpart would be doable, I guess. But of course it would break the API completely and should only be done in a new major release in my opinion. Using typedefs and offering a build-time flag to opt for C++11 types where applicable is an option.

A first attempt to replace some calls to `boost::bind` and `boost::lambda::bind` was made in https://github.com/orocos-toolchain/rtt/pull/103 (successor of https://github.com/orocos-toolchain/rtt/pull/98), but we had to revert it later in https://github.com/orocos-toolchain/rtt/pull/201 because of incompatibilities with Boost Lambda with newer Boost versions.

Using move semantics for passing data in port connections or for operation calls could be another valuable addition, but that would need to be designed and tested carefully in order to not break real-time applications.

It should be noted that Boost as a dependency cannot be eliminated completely because there are no equivalent replacements in modern C++ for things like [Boost Fusion](https://www.boost.org/doc/libs/1_61_0/libs/fusion/doc/html/) (used for operation calling) or [Boost Spirit](https://www.boost.org/doc/libs/1_61_0/libs/spirit/doc/html/) (used for Orocos scripting).

**Comment by haianos** [comment]
Hi @meyerj , thanks for the answer! :-) 

Yes, if that happens, it will break API and it should be a major release.
One reason to do so is more pragmatic than for performance reasons: it may come not natural in the future to remind to use boost::function thus not defining bindings by means of C++14 lambdas.

About Boost spirit: it's basically a parser, there are other alternatives nowadays. But I don't have a good reason about why some efforts should be spent there. Also, I would be interesting to know about how much Orocos scripts are currently used wrt Lua counterpart.
